version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: app
    working_dir: /var/www
    environment:
      DB_CONNECTION: ${DB_CONNECTION:-sqlite}
    volumes:
      - ./:/var/www
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
