version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    networks:
      - laravel

networks:
  laravel:
